### ISSUE TITLE
bug: misleading error for non-existent remote module

### ISSUE THREAD

**Issue by justsaft** [Vanilla-OS/Vib#147]
### Bug: Vib produces the following misleading error message when including a non-existent module `.yml` file as a remote module
```log
Building module [] of type []
Loading new plugin
panic: /usr//share/vib/plugins/.so: cannot open shared object file: No such file or directory
```

### Steps to reproduce
- Create a recipe.
- Add a module include statement similar to this.
```yaml
- name: packages-modules
    type: includes
    includes:
      - gh:vanilla-os/desktop-image:main:module/404-this-file-doesnt-exist.yml
```
- run `vib build recipe.yml`

### Expected behaviour
Simple error message that clarifies that a remote module wasn't found (just like there is for local modules (although I think those aren't generated by Vib directly)).

Using Vib version: v0.8.1
