### ISSUE TITLE
api: Add Source for single file

### ISSUE THREAD

**Issue by axtloss** [Vanilla-OS/Vib#18]
It may be useful to only download single files that are not in a git repo or tar files, the current Source and download api functions do not allow that.

**Comment by axtloss** [comment]
This should be relatively easy to implement as a newcomer, so I removed myself as the assignee
though i may just fix it if i come across it again while doing something else

**Comment by deepu9** [comment]
@axtloss I would like to work on it. Can you assign this to me. Thanks

**Comment by deepu9** [comment]
Thanks to @kbdharun for the below explanation on the isse:

Basically currently the source module supports importing a whole git repository (with options like tags, commits, etc) and tar archive.

What this feature request is for is to allow downloading single files (i.e. a config from somewhere, etc) instead of a git repo or a whole package archive (tar)

**What would be the module structure in the yml file?**

Current implementation for Git:

```yaml
- name: init
  type: shell
  source:
      type: git
      url: https://github.com/Vanilla-OS/website
      branch: v2
      commit: latest
  commands:
      - mv /sources/init /app
```

Current implementation for Tar:

```yaml
name: fswarn
type: shell
commands:
  - mkdir -p /boot/
  - cp /sources/fswarn-x86_64.squash /boot/fswarn.squash
source:
  type: tar
  url: https://github.com/Vanilla-OS/fswarn/releases/download/v1.0-1/fswarn.tar.xz
  checksum: 52f66710132138c21b81b56cb2d6edc7e59ad6eef4a4065b81af0f852d827dab
```

For a single file in this case it can be similar to the above tar case:

```yaml
name: some-name
type: shell
commands:
  - some-commands
source:
  type: file
  url: some-url to file
  checksum: some-checksum
```

For the implementation you can use Go's equivalent of something like wget or rsync to get the file and place it in the sources directory.

**Do we have an allowed list of files?**
Nope
