### ISSUE TITLE
Support generating changelogs

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/Vib#5]
Image-based operating systems, which are the target of Vib, are [often not just packages](https://github.com/Vanilla-OS/ABRoot/issues/115), and if they use Vib it's very likely they're using meson, go, cmake, make, shell scripts, or whatever to deliver software and customizations.

The idea is to allow image maintainers to add comments in the recipe, so as to automatically generate the changelog with the build, and use a prefix to define the version.

Here is an example:

```yaml
modules:
- name: init-setup
  type: shell
  commands:
  # v0.1: the PATH environment now supports listing binaries from /usr/local/bin
  - echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"' > /etc/environment
  - sed -i '4,10d' /etc/profile
  - apt update
  - apt upgrade -y
  - apt clean
  # v0.2: prevented snap from being installed as a dependency
  - apt-mark hold snapd gnome-software-plugin-snap

# v0.1: implemented the Vanilla Tools
- name: vanilla-tools
  type: shell
  source:
    type: tar
    # switch to production build once in production
    url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/continuous/vanilla-tools.tar.gz
  commands:
  - mkdir -p /usr/bin
  - cp /sources/vanilla-tools/lpkg /usr/bin/lpkg
  - cp /sources/vanilla-tools/cur-gpu /usr/bin/cur-gpu
  - chmod +x /usr/bin/lpkg
  - chmod +x /usr/bin/cur-gpu
```

Vib should be smart enough to generate a changelog for the greeter version which is `v0.2` in this case. It could also generate an extended version with all the comments grouped by version.
