### ISSUE TITLE
adds instruction is ignored

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/Vib#64]
The following image builds but both "adds" instructions are ignored.
```yml
name: Custom
id: custom

stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  adds:
  - srcdst:
    hello: /wow
  modules:

  - name: example-commands
    type: shell
    adds:
    - srcdst:
      hello: /wow
    commands:
    - echo Example output
```

~~Might be fixed by: # 63~~ (This only touches the copy command so it won't affect this)

**Comment by kbdharun** [comment]
I tested your sample recipe, replacing hello with a valid file in my local path, we don't support placing adds within modules so that's why your Containerfile didn't show it.

I have attached a working example of the adds directive in the current versions.

i.e.

```yml
name: Custom
id: custom

stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  adds:
  - srcdst:
      go.mod: /wow
  modules:
  - name: example-commands
    type: shell
    commands:
    - echo Example output
```

```Dockerfile
# Stage: build
FROM ghcr.io/vanilla-os/desktop:main AS build
ADD go.mod /wow
ADD includes.container /
ADD sources /sources
RUN echo Example output
```
