### ISSUE TITLE
copy instruction is ignored

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/Vib#65]
When using the following recipe:
```yml
name: Custom
id: custom

stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  modules:

  - name: example-commands
    type: shell
    copy:
    - paths:
      src: hello
      dst: /wow
    commands:
    - echo Example output
```

it builds successfully but the copy instruction is ignored. 
Might be fixed by: #63
